/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cConvert;

/**
 *
 * @author user
 */
public class Converter extends javax.swing.JFrame {

	double Kenyan_Shilling = 152.12;                 
	double USA_Dollar = 0.0090;
	double Canadian_Dollar = 0.011;
	double Nigerian_Naira = 3.65;
	double Brazilian_Real = 0.050;
	double Indian_Rupee = 0.67;

	/**
	 * Creates new form Converter
	 */
	public Converter() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jcmbCurrency = new javax.swing.JComboBox<>();
                jlblConvert = new javax.swing.JLabel();
                jtxtConvert = new javax.swing.JTextField();
                jbtnConvert = new javax.swing.JButton();
                jbtnRest = new javax.swing.JButton();
                jbtnExit = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Currency Converter");
                jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jcmbCurrency.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
                jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "USA", "Kenya", "Canada", "India", "Nigeria", "Brazil" }));
                jcmbCurrency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
                jcmbCurrency.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jcmbCurrencyActionPerformed(evt);
                        }
                });

                jlblConvert.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
                jlblConvert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jlblConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jtxtConvert.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
                jtxtConvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jtxtConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jbtnConvert.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
                jbtnConvert.setText("Convert");
                jbtnConvert.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbtnConvertActionPerformed(evt);
                        }
                });

                jbtnRest.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
                jbtnRest.setText("Reset");
                jbtnRest.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbtnRestActionPerformed(evt);
                        }
                });

                jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
                jbtnExit.setText("Exit");
                jbtnExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jbtnExitActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(85, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(239, 239, 239))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jbtnExit)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(73, 73, 73))))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnConvert)
                                                .addGap(257, 257, 257)
                                                .addComponent(jbtnRest))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(329, 329, 329)
                                                .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnConvert)
                                        .addComponent(jbtnRest)
                                        .addComponent(jbtnExit))
                                .addGap(39, 39, 39))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
                System.exit(0);
        }//GEN-LAST:event_jbtnExitActionPerformed

        private void jbtnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestActionPerformed
                jtxtConvert.setText(null);
		jlblConvert.setText(null);
		jcmbCurrency.setSelectedIndex(0);
        }//GEN-LAST:event_jbtnRestActionPerformed

        private void jbtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvertActionPerformed
                double British_Pound = Double.parseDouble(jtxtConvert.getText());
		if (jcmbCurrency.getSelectedItem().equals("Kenya")){
			String cConvert1 = String.format("KES %.2f", British_Pound * Kenyan_Shilling);
			jlblConvert.setText(cConvert1);
		}
		if (jcmbCurrency.getSelectedItem().equals("USA")){
			String cConvert1 = String.format("USA $ %.2f", British_Pound * USA_Dollar);
			jlblConvert.setText(cConvert1);
		}
		if (jcmbCurrency.getSelectedItem().equals("Canada")){
			String cConvert1 = String.format("CAD $ %.2f", British_Pound * Canadian_Dollar);
			jlblConvert.setText(cConvert1);
		}
		if (jcmbCurrency.getSelectedItem().equals("India")){
			String cConvert1 = String.format("INR ₹ %.2f", British_Pound * Indian_Rupee);
			jlblConvert.setText(cConvert1);
		}
		if (jcmbCurrency.getSelectedItem().equals("Nigeria")){
			String cConvert1 = String.format("NGN ₦ %.2f", British_Pound * Nigerian_Naira);
			jlblConvert.setText(cConvert1);
		}
		if (jcmbCurrency.getSelectedItem().equals("Brazil")){
			String cConvert1 = String.format("BRL R$ %.2f", British_Pound * Brazilian_Real);
			jlblConvert.setText(cConvert1);
		}
        }//GEN-LAST:event_jbtnConvertActionPerformed

        private void jcmbCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCurrencyActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jcmbCurrencyActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Converter().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JButton jbtnConvert;
        private javax.swing.JButton jbtnExit;
        private javax.swing.JButton jbtnRest;
        private javax.swing.JComboBox<String> jcmbCurrency;
        private javax.swing.JLabel jlblConvert;
        private javax.swing.JTextField jtxtConvert;
        // End of variables declaration//GEN-END:variables
}
